---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec
  
transport:
  name: winrm

platforms:
  - name: win10
    os_type: windows
    shell_type: powershell

suites:
  - name: default
    run_list:
      - recipe[vcruntime-wrapper::vc2008]
      - recipe[vcruntime-wrapper::vc2010]
      - recipe[vcruntime-wrapper::vc2010_x86]
      - recipe[vcruntime-wrapper::vc2015]
      - recipe[vcruntime-wrapper::vc2015_x86]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
